---
# Ansible Galaxy collections for the Dev Environment project
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: community.docker
    version: ">=3.0.0"
    source: https://galaxy.ansible.com

  - name: homebrew
    version: ">=0.1.0"
    source: https://galaxy.ansible.com

  - name: community.general
    version: ">=7.0.0"
    source: https://galaxy.ansible.com

  - name: ansible.posix
    version: ">=1.5.0"
    source: https://galaxy.ansible.com
