---
- name: Ansible Dev Environment Setup (Dynamic)
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Load group_vars/all.yml explicitly
      include_vars:
        file: group_vars/all.yml
      # No 'name:' here, so vars are loaded globally for this play

    - name: Debug loaded variables
      debug:
        msg: "enabled_roles: {{ enabled_roles | default('NOT DEFINED, using default list') }}"

  tasks:
    - name: Block for role execution
      block:
        - name: Iterate and run enabled roles
          include_role:
            name: "{{ item }}"
          tags: "{{ item }}"
          loop: "{{ enabled_roles | default(['os-detection', 'prerequisites', 'base-installs', 'docker-setup', 'shell-customize', 'nvim-setup', 'dev-envs', 'security-harden', 'cloud-init', 'fonts', 'terminals', 'gui-installs', 'nix-gui-installs']) }}"
      rescue:
        - name: Fallback if loop fails (e.g. item still undefined)
          debug:
            msg: "Loop failed, attempting to run roles individually based on defaults."
          # This is a fallback, ideally the loop should work.
          # For a true fallback, you'd list individual include_role tasks here.

  post_tasks:
    - name: Summary
      debug:
        msg:
          - "Setup complete for target_user: {{ target_user | default('N/A') }} on {{ ansible_hostname }}."
          - "Portainer available at http://{{ ansible_default_ipv4.address | default('N/A') }}:{{ portainer_port | default('N/A') }}."
          - "Run 'ansible-playbook site_dynamic.yml --tags <role_name>' for individual roles."

# Assisted by Cline on 2025-10-02.
