---
- name: Test os-detection role
  hosts: all
  become: false # os-detection typically doesn't need sudo
  gather_facts: true

  tasks:
    - name: Load group_vars/all.yml (if needed by os-detection)
      include_vars:
        file: group_vars/all.yml

    - name: Run os-detection role
      include_role: name=os-detection
      tags: os-detection

    - name: Debug gathered facts
      debug:
        msg: "OS Family: {{ ansible_os_family }}, Distribution: {{ ansible_distribution }}, Package Manager: {{ package_mgr | default('unknown') }}"
