---
# Docker Setup Role
# Installs Docker CE, Docker Compose v2, and deploys Portainer CE.
# Assisted by Cline (powered by xAI Grok model) on 2025-09-25.

- name: Install Docker dependencies (Debian)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: ansible_os_family == 'Debian'
  tags: docker-setup

- name: Add Docker GPG key (Debian)
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  when: ansible_os_family == 'Debian'
  tags: docker-setup

- name: Add Docker repository (Debian)
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
    state: present
  when: ansible_os_family == 'Debian'
  tags: docker-setup

- name: Install Docker CE (Debian)
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
  tags: docker-setup

- name: Install Docker on RedHat/Fedora/Rocky
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_os_family == 'RedHat'
  tags: docker-setup

- name: Install Docker on Arch
  pacman:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_os == 'Archlinux'
  tags: docker-setup

- name: Install Docker on macOS
  homebrew:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_os == 'Darwin'
  tags: docker-setup

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  when: ansible_os_family in ['Debian', 'RedHat'] or ansible_os == 'Archlinux'
  tags: docker-setup

- name: Add user to docker group
  user:
    name: "{{ target_user }}"
    groups: docker
    append: yes
  tags: docker-setup

- name: Deploy Portainer CE container
  docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: always
    ports:
      - "{{ portainer_port }}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  tags: docker-setup

- name: Deploy Syncthing container
  docker_container:
    name: syncthing
    image: syncthing/syncthing:latest
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ syncthing_gui_port }}:8384"
      - "{{ syncthing_sync_port }}:22000/tcp"
      - "{{ syncthing_udp_port }}:21027/udp"
    volumes:
      - "{{ target_user_home }}/{{ user_syncthing_data }}:/var/syncthing"
      - "{{ target_user_home }}/{{ user_docker_dir }}/syncthing:/config"
    env:
      PUID: "{{ ansible_user_uid | default(1000) }}"
      PGID: "{{ ansible_user_gid | default(1000) }}"
  tags: docker-setup

- name: Copy Syncthing docker-compose.yml to user dir
  copy:
    src: files/docker-services/syncthing/docker-compose.yml
    dest: "{{ target_user_home }}/{{ user_docker_dir }}/syncthing/docker-compose.yml"
    mode: '0644'
  become_user: "{{ target_user }}"
  tags: docker-setup

- name: Copy Syncthing docker-compose.yml to skel
  copy:
    src: files/docker-services/syncthing/docker-compose.yml
    dest: "/etc/skel/{{ user_docker_dir }}/syncthing/docker-compose.yml"
    mode: '0644'
  tags: docker-setup

- name: Debug Docker setup complete
  debug:
    msg: "Docker installed, Portainer on {{ portainer_port }}, Syncthing on {{ syncthing_gui_port }}."
  tags: docker-setup
